apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: {{ .Values.app.name }}
  type: NodePort
  selector:
    app: {{ .Values.app.name }}